export * from './GenderChart';
export * from './AgeChart';
export * from './AreaChart';
export * from './CityChart';
export * from './WeekChart';
export * from './DistributionCityChart'
export * from './DistributionBairroChart'
export * from './IndicadosGrowth'
export * from './RedeGrowth'
